### ISSUE TITLE
error Missing onError handler for invocation 'building-schema'

### ISSUE THREAD

**Issue by jonohewitt** [PaulieScanlon/fauna-gatsby-comments#8]
Hi, thanks a lot for this tutorial! Everything was going great until I tried to run the server locally after installing with npm, where I got this error:

```
error Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value: Date.'. Stacktrace was 'Error: Cannot create as TypeComposer the following value: Date.
    at SchemaComposer.createTempTC (/fauna-gatsby-comments/node_modules/graphql-compose/lib/SchemaComposer.js:365:11)
    at SchemaComposer.addAsComposer (/fauna-gatsby-comments/node_modules/graphql-compose/lib/SchemaComposer.js:563:27)
    at createSchemaComposer (/fauna-gatsby-comments/node_modules/gatsby/src/schema/schema-composer.js:16:18)
    at build (/fauna-gatsby-comments/node_modules/gatsby/src/schema/index.js:104:26)
    at buildSchema (/fauna-gatsby-comments/node_modules/gatsby/src/services/build-schema.ts:19:3)'
not finished building schema - 8.663s
```

It built without any errors on Netlify. Managed to get around it by using yarn instead of npm but thought I'd mention it in case it's helpful! Thanks again for the tutorial.

**Comment by perezgildardo** [comment]
Not related to the repo but you can use:
`> npm cache clean --force && rm -rf node_modules && rm -rf package-lock.json && yarn install && gatsby develop`
